from ff1tiles import *

expand_mountains = [
    [[MOUNTAIN, "_", "_",
      "_", "_", "_",
      "_", "_", "_"],
     MOUNTAIN],
    [["_", MOUNTAIN, "_",
      "_", "_", "_",
      "_", "_", "_"],
     MOUNTAIN],
    [["_", "_", MOUNTAIN,
      "_", "_", "_",
      "_", "_", "_"],
     MOUNTAIN],

    [["_", "_", "_",
      MOUNTAIN, "_", "_",
      "_", "_", "_"],
     MOUNTAIN],
    [["_", "_", "_",
      "_", MOUNTAIN, "_",
      "_", "_", "_"],
     MOUNTAIN],
    [["_", "_", "_",
      "_", "_", MOUNTAIN,
      "_", "_", "_"],
     MOUNTAIN],

    [["_", "_", "_",
      "_", "_", "_",
      MOUNTAIN, "_", "_"],
     MOUNTAIN],
    [["_", "_", "_",
      "_", "_", "_",
      "_", MOUNTAIN, "_"],
     MOUNTAIN],
    [["_", "_", "_",
      "_", "_", "_",
      "_", "_", MOUNTAIN],
     MOUNTAIN],
]

expand_oceans = [
    [[OCEAN, "_", "_",
      "_", "_", "_",
      "_", "_", "_"],
     OCEAN],
    [["_", OCEAN, "_",
      "_", "_", "_",
      "_", "_", "_"],
     OCEAN],
    [["_", "_", OCEAN,
      "_", "_", "_",
      "_", "_", "_"],
     OCEAN],

    [["_", "_", "_",
      OCEAN, "_", "_",
      "_", "_", "_"],
     OCEAN],
    [["_", "_", "_",
      "_", OCEAN, "_",
      "_", "_", "_"],
     OCEAN],
    [["_", "_", "_",
      "_", "_", OCEAN,
      "_", "_", "_"],
     OCEAN],

    [["_", "_", "_",
      "_", "_", "_",
      OCEAN, "_", "_"],
     OCEAN],
    [["_", "_", "_",
      "_", "_", "_",
      "_", OCEAN, "_"],
     OCEAN],
    [["_", "_", "_",
      "_", "_", "_",
      "_", "_", OCEAN],
     OCEAN],
]

connect_diagonals = [
    [["*", RIVER, "_",
     "*", "_", RIVER,
     "*", "*", "*"],
     RIVER],
    [["_", RIVER, "*",
     RIVER, "_", "*",
     "*", "*", "*"],
     RIVER],
    [["*", OCEAN, "_",
     "*", "_", OCEAN,
     "*", "*", "*"],
     OCEAN],
    [["_", OCEAN, "*",
     OCEAN, "_", "*",
     "*", "*", "*"],
     OCEAN],
    [["*", MOUNTAIN, "_",
     "*", "_", MOUNTAIN,
     "*", "*", "*"],
     MOUNTAIN],
    [["_", MOUNTAIN, "*",
     MOUNTAIN, "_", "*",
     "*", "*", "*"],
     MOUNTAIN],
]

smooth_rivers = [
    [["_",      RIVER,    "_",
     MOUNTAIN, RIVER,    MOUNTAIN,
     MOUNTAIN, MOUNTAIN, MOUNTAIN],
     MOUNTAIN],
    [[MOUNTAIN, MOUNTAIN, "_",
     MOUNTAIN, RIVER,    RIVER,
     MOUNTAIN, MOUNTAIN, "_"],
     MOUNTAIN],
    [[MOUNTAIN, MOUNTAIN, MOUNTAIN,
     MOUNTAIN, RIVER,    MOUNTAIN,
     "_",      RIVER,    "_"],
     MOUNTAIN],
    [["_",   MOUNTAIN, MOUNTAIN,
     RIVER, RIVER,    MOUNTAIN,
     "_",   MOUNTAIN, MOUNTAIN],
     MOUNTAIN],
    [["_",  RIVER, "_",
     LAND, RIVER, LAND,
     LAND, LAND,  LAND],
     LAND],
    [[LAND, LAND, "_",
     LAND, RIVER, RIVER,
     LAND, LAND, "_"],
     LAND],
    [[LAND, LAND,  LAND,
     LAND, RIVER, LAND,
     "_",  RIVER, "_"],
     LAND],
    [["_",   LAND,  LAND,
     RIVER, RIVER, LAND,
     "_",   LAND,  LAND],
     LAND],
    [["_",   MOUNTAIN, "_",
     RIVER, MOUNTAIN, RIVER,
     RIVER, RIVER,    RIVER],
     RIVER],
    [[RIVER, RIVER,    "_",
     RIVER, MOUNTAIN, MOUNTAIN,
     RIVER, RIVER,    "_"],
     RIVER],
    [[RIVER, RIVER,    RIVER,
     RIVER, MOUNTAIN, RIVER,
     "_",   MOUNTAIN, "_"],
     RIVER],
    [["_",      RIVER,    RIVER,
     MOUNTAIN, MOUNTAIN, RIVER,
     "_",      RIVER,    RIVER],
     RIVER],
]

fixup_mountains = [
    [["*", "_",      "*",
      "_", MOUNTAIN, "_",
      "*", "*",      "*"],
     LAND],
    [["*", "_",      "*",
      "*", MOUNTAIN, "_",
      "*", "_",      "*"],
     LAND],
    [["*", "*",      "*",
      "_", MOUNTAIN, "_",
      "*", "_",      "*"],
     LAND],
    [["*", "_",      "*",
      "_", MOUNTAIN, "*",
      "*", "_",      "*"],
     LAND],
]


apply_shores1 = [
    [["*", "*",   "*",
      "*", OCEAN, LAND,
      "*", LAND,  "*"],
     SHORE_NW],

    [["*", "*",    "*",
      LAND, OCEAN, "*",
      "*", LAND,   "*"],
     SHORE_NE],

    [["*",  LAND,  "*",
      LAND, OCEAN, "*",
      "*",  "*",   "*"],
     SHORE_SE],

    [["*", LAND,   "*",
      "*", OCEAN,  LAND,
      "*",  "*",   "*"],
     SHORE_SW],
]

apply_shores2 = [
    [["*", OCEAN,  "*",
      "*", LAND,   OCEAN,
      "*", OCEAN,  "*"],
     LAND],

    [["*", "*",    "*",
      OCEAN, LAND, OCEAN,
      "*", OCEAN,  "*"],
     LAND],

    [["*", OCEAN,  "*",
      OCEAN, LAND, "*",
      "*", OCEAN,  "*"],
     LAND],

    [["*", OCEAN,  "*",
      OCEAN, LAND, OCEAN,
      "*", "*",    "*"],
     LAND],

    [["*", "*",   "*",
      "*", LAND,  OCEAN,
      "*", OCEAN, "*"],
     SHORE_SE],

    [["*", "*",    "*",
      OCEAN, LAND, "*",
      "*", OCEAN,  "*"],
     SHORE_SW],

    [["*", OCEAN,  "*",
      OCEAN, LAND, "*",
      "*", "*",    "*"],
     SHORE_NW],

    [["*", OCEAN,  "*",
      "*", LAND,   OCEAN,
      "*", "*",    "*"],
     SHORE_NE],
]

apply_shores3 = [
    [["*", "*",   "*",
      "*", OCEAN, LAND,
      "*", "*",   "*"],
     SHORE_W],
    [["*",  "*",   "*",
      LAND, OCEAN, "*",
      "*",  "*",   "*"],
     SHORE_E],
    [["*", "*",   "*",
      "*", OCEAN, "*",
      "*", LAND,  "*"],
     SHORE_N],
    [["*", LAND,   "*",
      "*", OCEAN,  "*",
      "*", "*",    "*",],
     SHORE_S],
]

mountain_borders = [
    [["*", "*",       "*",
      "*", MOUNTAIN,  "_",
      "*",       "_", "*"],
     MOUNTAIN_SE],

    [["*", "*",       "*",
      "_", MOUNTAIN,  "*",
      "*",       "_", "*"],
     MOUNTAIN_SW],

    [["*", "_",       "*",
      "_", MOUNTAIN,  "*",
      "*",       "*", "*"],
     MOUNTAIN_NW],

    [["*", "_",       "*",
      "*", MOUNTAIN,  "_",
      "*",       "*", "*"],
     MOUNTAIN_NE],


    [["*", "*",       "*",
      "*", MOUNTAIN,  "_",
      "*",       "*", "*"],
     MOUNTAIN_E],

    [["*", "*",       "*",
      "_", MOUNTAIN,  "*",
      "*",       "*", "*"],
     MOUNTAIN_W],

    [["*", "_",       "*",
      "*", MOUNTAIN,  "*",
      "*",       "*", "*"],
     MOUNTAIN_N],

    [["*", "*",       "*",
      "*", MOUNTAIN,  "*",
      "*",       "_", "*"],
     MOUNTAIN_S],
]

river_borders = [
    [["*", "_",   "*",
     "_", RIVER, RIVER,
     "*", RIVER,   "*"],
     RIVER_NW],

    [["*", "_",   "*",
     RIVER, RIVER, "_",
       "*", RIVER,   "*"],
     RIVER_NE],

    [["*",  RIVER,   "*",
     RIVER, RIVER, "_",
       "*", "_",   "*"],
     RIVER_SE],

    [["*",  RIVER,   "*",
      "_",  RIVER, RIVER,
      "*", "_",   "*"],
     RIVER_SW],
]

desert_borders = [
    [["*", "_",   "*",
     "_", DESERT, DESERT,
     "*", DESERT,   "*"],
     DESERT_NW],

    [["*", "_",   "*",
     DESERT, DESERT, "_",
       "*", DESERT,   "*"],
     DESERT_NE],

    [["*",  DESERT,   "*",
     DESERT, DESERT, "_",
       "*", "_",   "*"],
     DESERT_SE],

    [["*",  DESERT,   "*",
      "_",  DESERT, DESERT,
      "*", "_",   "*"],
     DESERT_SW],
]

marsh_borders = [
    [["*", "_",   "*",
     "_", MARSH, MARSH,
     "*", MARSH,   "*"],
     MARSH_NW],

    [["*", "_",   "*",
     MARSH, MARSH, "_",
       "*", MARSH,   "*"],
     MARSH_NE],

    [["*",  MARSH,   "*",
     MARSH, MARSH, "_",
       "*", "_",   "*"],
     MARSH_SE],

    [["*",  MARSH,   "*",
      "_",  MARSH, MARSH,
      "*", "_",   "*"],
     MARSH_SW],
]

grass_borders = [
    [["*", "_",   "*",
     "_", GRASS, GRASS,
     "*", GRASS,   "*"],
     GRASS_NW],

    [["*", "_",   "*",
     GRASS, GRASS, "_",
       "*", GRASS,   "*"],
     GRASS_NE],

    [["*",  GRASS,   "*",
     GRASS, GRASS, "_",
       "*", "_",   "*"],
     GRASS_SE],

    [["*",  GRASS,   "*",
      "_",  GRASS, GRASS,
      "*", "_",   "*"],
     GRASS_SW],
]

forest_borders = [
    [["*", "*",       "*",
      "*", FOREST,  "_",
      "*",       "_", "*"],
     FOREST_SE],

    [["*", "*",       "*",
      "_", FOREST,  "*",
      "*",       "_", "*"],
     FOREST_SW],

    [["*", "_",       "*",
      "_", FOREST,  "*",
      "*",       "*", "*"],
     FOREST_NW],

    [["*", "_",       "*",
      "*", FOREST,  "_",
      "*",       "*", "*"],
     FOREST_NE],


    [["*", "*",       "*",
      "*", FOREST,  "_",
      "*",       "*", "*"],
     FOREST_E],

    [["*", "*",       "*",
      "_", FOREST,  "*",
      "*",       "*", "*"],
     FOREST_W],

    [["*", "_",       "*",
      "*", FOREST,  "*",
      "*",       "*", "*"],
     FOREST_N],

    [["*", "*",       "*",
      "*", FOREST,  "*",
      "*",       "_", "*"],
     FOREST_S],
]
