from ff1tiles import *

CONERIA_CITY = [
    [None, None, CONERIA_CASTLE_TOP_W, CONERIA_CASTLE_TOP_E, None, None],
    [None, CITY_WALL_NW, CONERIA_CASTLE_MID_W, CONERIA_CASTLE_MID_E, CITY_WALL_NE, None],
    [CITY_WALL_W1, CITY_WALL_W2, CONERIA_CASTLE_ENTRANCE_W, CONERIA_CASTLE_ENTRANCE_E, CITY_WALL_E2, CITY_WALL_E1],
    [CITY_WALL_W3, CONERIA, CITY_PAVED, CITY_PAVED, CONERIA, CITY_WALL_E3],
    [CITY_WALL_W4, CONERIA, CITY_PAVED, CITY_PAVED, CONERIA, CITY_WALL_E4],
    [CITY_WALL_W5, CONERIA, CITY_PAVED, CITY_PAVED, CONERIA, CITY_WALL_E5],
    [CITY_WALL_SW2, CITY_WALL_GATE_W, CITY_PAVED, CITY_PAVED, CITY_WALL_GATE_E, CITY_WALL_SE2],
    ]

TEMPLE_OF_FIENDS = [
    [None, TOF_TOP_W, TOF_TOP_E, None],
    [TOF_BOTTOM_W, TOF_ENTRANCE_W, TOF_ENTRANCE_E, TOF_BOTTOM_E],
]

PRAVOKA_CITY = [
    [None, CITY_WALL_NW, CITY_WALL_N, CITY_WALL_NE, None],
    [CITY_WALL_W1, CITY_WALL_W2, PRAVOKA, CITY_WALL_E2, CITY_WALL_E1],
    [CITY_WALL_W3, PRAVOKA, CITY_PAVED, PRAVOKA, CITY_WALL_E3],
    [CITY_WALL_SW1, CITY_WALL_GATE_W, CITY_PAVED, CITY_WALL_GATE_E, CITY_WALL_SE1],
]

ELFLAND_CASTLE = [
    [SMALL_CASTLE_TOP_W, SMALL_CASTLE_TOP_W],
    [ELFLAND_CASTLE_W, ELFLAND_CASTLE_E],
]

ASTOS_CASTLE = [
    [SMALL_CASTLE_TOP_W, SMALL_CASTLE_TOP_W],
    [ASTOS_CASTLE_W, ASTOS_CASTLE_E],
]

ORDEALS_CASTLE = [
    [SMALL_CASTLE_TOP_W, SMALL_CASTLE_TOP_W],
    [ORDEALS_CASTLE_W, ORDEALS_CASTLE_E],
]

ELFLAND_TOWN = [
    [ELFLAND, None, None, ELFLAND],
    [ELFLAND, None, None, ELFLAND],
]

ELFLAND_TOWN_CASTLE = [
    [None, SMALL_CASTLE_TOP_W, SMALL_CASTLE_TOP_W, None],
    [ELFLAND, ELFLAND_CASTLE_W, ELFLAND_CASTLE_E, ELFLAND],
    [ELFLAND, None, None, ELFLAND],
]


MELMOND_TOWN = [
    [MELMOND, None],
    [MELMOND, MELMOND]
]

ONRAC_TOWN = [
    [ONRAC, ONRAC],
    [ONRAC, ONRAC]
]

LEIFEN_CITY = [
    [None, CITY_WALL_NW, CITY_WALL_N, CITY_WALL_NE, None],
    [CITY_WALL_W1, CITY_WALL_W2, LEIFEN, CITY_WALL_E2, CITY_WALL_E1],
    [CITY_WALL_W3, LEIFEN, LEIFEN, LEIFEN, CITY_WALL_E3],
    [CITY_WALL_SW1, CITY_WALL_GATE_W, CITY_PAVED, CITY_WALL_GATE_E, CITY_WALL_SE1],
]

CRESCENT_LAKE_CITY = [
    [None, CITY_WALL_NW, CITY_WALL_N, CITY_WALL_NE, None],
    [CITY_WALL_W1, CITY_WALL_W2, CITY_PAVED, CITY_WALL_E2, CITY_WALL_E1],
    [CITY_WALL_W3, CITY_PAVED, CRESCENT_LAKE, CRESCENT_LAKE, CITY_WALL_E3],
    [CITY_WALL_W4, CRESCENT_LAKE, CITY_PAVED, CRESCENT_LAKE, CITY_WALL_E4],
    [CITY_WALL_W5, CRESCENT_LAKE, CITY_PAVED, CITY_PAVED, CITY_WALL_E5],
    [CITY_WALL_SW2, CITY_WALL_GATE_W, CITY_PAVED, CITY_WALL_GATE_E, CITY_WALL_SE2],
    ]

GAIA_TOWN = [
    [None, GAIA, GAIA],
    [GAIA, GAIA, None],
]

MIRAGE_TOWER = [
    [MIRAGE_TOP, None],
    [MIRAGE_BOTTOM, MIRAGE_SHADOW],
    ]

VOLCANO = [
    [VOLCANO_TOP_W, VOLCANO_TOP_E],
    [VOLCANO_BASE_W, VOLCANO_BASE_E],
]

OASIS = [
    [None, DESERT_NW, DESERT_NE],
    [DESERT_NW, CARAVAN_DESERT, DESERT_SE],
    [DESERT_SW, DESERT_SE, None]
]
