from ff1tiles import *

VANILLA_CORNERIA = [
    [None, None, CORNERIA_CASTLE_TOP_W, CORNERIA_CASTLE_TOP_E, None, None],
    [None, CITY_WALL_NW, CORNERIA_CASTLE_MID_W, CORNERIA_CASTLE_MID_E, CITY_WALL_NE, None],
    [CITY_WALL_W1, CITY_WALL_W2, CORNERIA_CASTLE_ENTRANCE_W, CORNERIA_CASTLE_ENTRANCE_E, CITY_WALL_E2, CITY_WALL_E1],
    [CITY_WALL_W3, None, None, None, None, CITY_WALL_E3],
    [CITY_WALL_W4, None, None, None, None, CITY_WALL_E4],
    [CITY_WALL_W5, None, None, None, None, CITY_WALL_E5],
    [CITY_WALL_SW2, CITY_WALL_GATE_W, None, None, CITY_WALL_GATE_E, CITY_WALL_SE2],
    ]

MIRAGE_TOWER = [
    [MIRAGE_TOP, None],
    [MIRAGE_BOTTOM, MIRAGE_SHADOW],
    ]

VOLCANO = [
    [VOLCANO_TOP_W, VOLCANO_TOP_E],
    [VOLCANO_BASE_W, VOLCANO_BASE_E],
]
