LAND = 0x00
CONERIA_CASTLE_ENTRANCE_W = 0x01
CONERIA_CASTLE_ENTRANCE_E = 0x02
FOREST_NW = 0x03
FOREST_N = 0x04
FOREST_NE = 0x05
SHORE_SE = 0x06
SHORE_S = 0x07
SHORE_SW = 0x08
CONERIA_CASTLE_TOP_W = 0x09
CONERIA_CASTLE_TOP_E = 0x0A
SMALL_CASTLE_TOP_W = 0x0B
SMALL_CASTLE_TOP_E = 0x0C
MIRAGE_TOP = 0x0D
EARTH_CAVE = 0x0E
DOCK_W = 0x0F
MOUNTAIN_NW = 0x10
MOUNTAIN_N = 0x11
MOUNTAIN_NE = 0x12
FOREST_W = 0x13
FOREST = 0x14
FOREST_E = 0x15
SHORE_E = 0x16
OCEAN = 0x17
SHORE_W = 0x18
CONERIA_CASTLE_MID_W = 0x19
CONERIA_CASTLE_MID_E = 0x1A
ELFLAND_CASTLE_W = 0x1B
ELFLAND_CASTLE_E = 0x1C
MIRAGE_BOTTOM = 0x1D
MIRAGE_SHADOW = 0x1E
DOCK_E = 0x1F
MOUNTAIN_W = 0x20
MOUNTAIN = 0x21
MOUNTAIN_E = 0x22
FOREST_SW = 0x23
FOREST_S = 0x24
FOREST_SE = 0x25
SHORE_NE = 0x26
SHORE_N = 0x27
SHORE_NW = 0x28
ASTOS_CASTLE_W = 0x29
ASTOS_CASTLE_E = 0x2A
ICE_CAVE = 0x2B
CITY_WALL_NW = 0x2C
CITY_WALL_N = 0x2D
CITY_WALL_NE = 0x2E
DWARF_CAVE = 0x2F
MOUNTAIN_SW = 0x30
MOUNTAIN_S = 0x31
MATOYAS_CAVE = 0x32
MOUNTAIN_SE = 0x33
TITAN_CAVE_E = 0x34
TITAN_CAVE_W = 0x35
CARAVAN_DESERT = 0x36
AIRSHIP_DESERT = 0x37
ORDEALS_CASTLE_W = 0x38
ORDEALS_CASTLE_E = 0x39
SARDAS_CAVE = 0x3A
CITY_WALL_W1 = 0x3B
CITY_WALL_W2 = 0x3C
CITY_PAVED = 0x3D
CITY_WALL_E2 = 0x3E
CITY_WALL_E1 = 0x3F
RIVER_NW = 0x40
RIVER_NE = 0x41
DESERT_NW = 0x42
DESERT_NE = 0x43
RIVER = 0x44
DESERT = 0x45
WATERFALL = 0x46
TOF_TOP_W = 0x47
TOF_TOP_E = 0x48
CONERIA = 0x49
PRAVOKA = 0x4A
CITY_WALL_W3 = 0x4B
ELFLAND = 0x4C
MELMOND = 0x4D
CRESCENT_LAKE = 0x4E
CITY_WALL_E3 = 0x4F
RIVER_SW = 0x50
RIVER_SE = 0x51
DESERT_SW = 0x52
DESERT_SE = 0x53
GRASS = 0x54
MARSH = 0x55
TOF_BOTTOM_W = 0x56
TOF_ENTRANCE_W = 0x57
TOF_ENTRANCE_E = 0x58
TOF_BOTTOM_E = 0x59
GAIA = 0x5A
CITY_WALL_W4 = 0x5B
CITY_WALL_SW1 = 0x5C
ONRAC = 0x5D
CITY_WALL_SE1 = 0x5E
CITY_WALL_E4 = 0x5F
GRASS_NW = 0x60
GRASS_NE = 0x61
MARSH_NW = 0x62
MARSH_NE = 0x63
VOLCANO_TOP_W = 0x64
VOLCANO_TOP_E = 0x65
CARDIA_2 = 0x66
CARDIA_3 = 0x67
CARDIA_4 = 0x68
CARDIA_5 = 0x69
CARDIA_1 = 0x6A
CITY_WALL_W5 = 0x6B
BAHAMUTS_CAVE = 0x6C
LEFEIN = 0x6D
MARSH_CAVE = 0x6E
CITY_WALL_E5 = 0x6F
GRASS_SW = 0x70
GRASS_SE = 0x71
MARSH_SW = 0x72
MARSH_SE = 0x73
VOLCANO_BASE_W = 0x74
VOLCANO_BASE_E = 0x75
LAND_NO_FIGHT = 0x76
DOCK_SE = 0x77
DOCK_S = 0x78
DOCK_SW = 0x79
DOCK_SQ = 0x7A
CITY_WALL_SW2 = 0x7B
CITY_WALL_S = 0x7C
CITY_WALL_GATE_W = 0x7D
CITY_WALL_GATE_E = 0x7E
CITY_WALL_SE2 = 0x7F

ALL_TILES = [
    LAND,
    CONERIA_CASTLE_ENTRANCE_W,
    CONERIA_CASTLE_ENTRANCE_E,
    FOREST_NW,
    FOREST_N,
    FOREST_NE,
    SHORE_SE,
    SHORE_S,
    SHORE_SW,
    CONERIA_CASTLE_TOP_W,
    CONERIA_CASTLE_TOP_E,
    SMALL_CASTLE_TOP_W,
    SMALL_CASTLE_TOP_E,
    MIRAGE_TOP,
    EARTH_CAVE,
    DOCK_W,
    MOUNTAIN_NW,
    MOUNTAIN_N,
    MOUNTAIN_NE,
    FOREST_W,
    FOREST,
    FOREST_E,
    SHORE_E,
    OCEAN,
    SHORE_W,
    CONERIA_CASTLE_MID_W,
    CONERIA_CASTLE_MID_E,
    ELFLAND_CASTLE_W,
    ELFLAND_CASTLE_E,
    MIRAGE_BOTTOM,
    MIRAGE_SHADOW,
    DOCK_E,
    MOUNTAIN_W,
    MOUNTAIN,
    MOUNTAIN_E,
    FOREST_SW,
    FOREST_S,
    FOREST_SE,
    SHORE_NE,
    SHORE_N,
    SHORE_NW,
    ASTOS_CASTLE_W,
    ASTOS_CASTLE_E,
    ICE_CAVE,
    CITY_WALL_NW,
    CITY_WALL_N,
    CITY_WALL_NE,
    DWARF_CAVE,
    MOUNTAIN_SW,
    MOUNTAIN_S,
    MATOYAS_CAVE,
    MOUNTAIN_SE,
    TITAN_CAVE_E,
    TITAN_CAVE_W,
    CARAVAN_DESERT,
    AIRSHIP_DESERT,
    ORDEALS_CASTLE_W,
    ORDEALS_CASTLE_E,
    SARDAS_CAVE,
    CITY_WALL_W1,
    CITY_WALL_W2,
    CITY_PAVED,
    CITY_WALL_E2,
    CITY_WALL_E1,
    RIVER_NW,
    RIVER_NE,
    DESERT_NW,
    DESERT_NE,
    RIVER,
    DESERT,
    WATERFALL,
    TOF_TOP_W,
    TOF_TOP_E,
    CONERIA,
    PRAVOKA,
    CITY_WALL_W3,
    ELFLAND,
    MELMOND,
    CRESCENT_LAKE,
    CITY_WALL_E3,
    RIVER_SW,
    RIVER_SE,
    DESERT_SW,
    DESERT_SE,
    GRASS,
    MARSH,
    TOF_BOTTOM_W,
    TOF_ENTRANCE_W,
    TOF_ENTRANCE_E,
    TOF_BOTTOM_E,
    GAIA,
    CITY_WALL_W4,
    CITY_WALL_SW1,
    ONRAC,
    CITY_WALL_SE1,
    CITY_WALL_E4,
    GRASS_NW,
    GRASS_NE,
    MARSH_NW,
    MARSH_NE,
    VOLCANO_TOP_W,
    VOLCANO_TOP_E,
    CARDIA_2,
    CARDIA_3,
    CARDIA_4,
    CARDIA_5,
    CARDIA_1,
    CITY_WALL_W5,
    BAHAMUTS_CAVE,
    LEFEIN,
    MARSH_CAVE,
    CITY_WALL_E5,
    GRASS_SW,
    GRASS_SE,
    MARSH_SW,
    MARSH_SE,
    VOLCANO_BASE_W,
    VOLCANO_BASE_E,
    LAND_NO_FIGHT,
    DOCK_SE,
    DOCK_S,
    DOCK_SW,
    DOCK_SQ,
    CITY_WALL_SW2,
    CITY_WALL_S,
    CITY_WALL_GATE_W,
    CITY_WALL_GATE_E,
    CITY_WALL_SE2,
]

LAND_REGION = 0
OCEAN_REGION = 1
RIVER_REGION = 2
GRASS_REGION = 3
MARSH_REGION = 4
MOUNTAIN_REGION = 5
FOREST_REGION = 6
DESERT_REGION = 7
MISC_REGION = 8

pre_shore_region_types = [
    [LAND, SHORE_NW, SHORE_NE, SHORE_SW, SHORE_SE],
    [OCEAN, SHORE_W, SHORE_N, SHORE_E, SHORE_S],
    [RIVER, RIVER_NW, RIVER_NE, RIVER_SW, RIVER_SE],
    [GRASS, GRASS_NW, GRASS_NE, GRASS_SW, GRASS_SE],
    [MARSH, MARSH_NW, MARSH_NE, MARSH_SW, MARSH_SE],
    [MOUNTAIN, MOUNTAIN_NW, MOUNTAIN_N, MOUNTAIN_NE,
     MOUNTAIN_W, MOUNTAIN_E,
     MOUNTAIN_SW, MOUNTAIN_S, MOUNTAIN_SE],
    [FOREST, FOREST_NW, FOREST_N, FOREST_NE,
     FOREST_W, FOREST_E,
     FOREST_SW, FOREST_S, FOREST_SE],
    [DESERT, DESERT_NW, DESERT_NE, DESERT_SW, DESERT_SE],
    []
]

pre_shore_region_map = {}
for j,r in enumerate(pre_shore_region_types):
    for i in r:
        pre_shore_region_map[i] = j
for i in ALL_TILES:
    if i not in pre_shore_region_map:
        pre_shore_region_map[i] = MISC_REGION

post_shore_region_types = [
    [LAND],
    [OCEAN, SHORE_W, SHORE_N, SHORE_E, SHORE_S, SHORE_NW, SHORE_NE, SHORE_SW, SHORE_SE],
    [RIVER, RIVER_NW, RIVER_NE, RIVER_SW, RIVER_SE],
    [GRASS, GRASS_NW, GRASS_NE, GRASS_SW, GRASS_SE],
    [MARSH, MARSH_NW, MARSH_NE, MARSH_SW, MARSH_SE],
    [MOUNTAIN, MOUNTAIN_NW, MOUNTAIN_N, MOUNTAIN_NE,
     MOUNTAIN_W, MOUNTAIN_E,
     MOUNTAIN_SW, MOUNTAIN_S, MOUNTAIN_SE,
     EARTH_CAVE, ICE_CAVE, DWARF_CAVE, MATOYAS_CAVE, SARDAS_CAVE, TITAN_CAVE_E, TITAN_CAVE_W],
    [FOREST, FOREST_NW, FOREST_N, FOREST_NE,
     FOREST_W, FOREST_E,
     FOREST_SW, FOREST_S, FOREST_SE],
    [DESERT, DESERT_NW, DESERT_NE, DESERT_SW, DESERT_SE],
    []
]
post_shore_region_map = {}
for j,r in enumerate(post_shore_region_types):
    for i in r:
        post_shore_region_map[i] = j
for i in ALL_TILES:
    if i not in post_shore_region_map:
        post_shore_region_map[i] = MISC_REGION

WALKABLE_REGION = 0
SAILING_REGION = 1
CANOE_REGION = 2

traversable_region_types = [
    [LAND, GRASS, GRASS_NW, GRASS_NE, GRASS_SW, GRASS_SE,
     MARSH, MARSH_NW, MARSH_NE, MARSH_SW, MARSH_SE,
     FOREST, FOREST_NW, FOREST_N, FOREST_NE,
     FOREST_W, FOREST_E,
     FOREST_SW, FOREST_S, FOREST_SE,
     SHORE_NW, SHORE_NE, SHORE_SW, SHORE_SE,
     DESERT, DESERT_NW, DESERT_NE, DESERT_SW, DESERT_SE,
     CITY_PAVED],
    [OCEAN, SHORE_W, SHORE_N, SHORE_E, SHORE_S],
    [RIVER, RIVER_NW, RIVER_NE, RIVER_SW, RIVER_SE],
]
traversable_region_map = {}
for j,r in enumerate(traversable_region_types):
    for i in r:
        traversable_region_map[i] = j
for i in ALL_TILES:
    if i not in traversable_region_map:
        traversable_region_map[i] = MISC_REGION
